# Introduction

In this notebook, we will do a comprehensive analysis of the Android app market by comparing thousands of apps in the Google Play store.

# About the Dataset of Google Play Store Apps & Reviews

**Data Source:** <br>
App and review data was scraped from the Google Play Store by Lavanya Gupta in 2018. Original files listed [here](
https://www.kaggle.com/lava18/google-play-store-apps).

# Import Statements

In [234]:
import pandas as pd
import plotly.express as px

# Notebook Presentation

In [235]:
# Show numeric output in decimal format e.g., 2.15
pd.options.display.float_format = '{:,.2f}'.format

# Read the Dataset

In [236]:
df_apps = pd.read_csv('apps.csv')
df_apps.head()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Android_Ver
0,Ak Parti Yardım Toplama,SOCIAL,NaN,0,8.70,0,Paid,$13.99,Teen,Social,"July 28, 2017",4.1 and up
1,Ain Arabic Kids Alif Ba ta,FAMILY,NaN,0,33.00,0,Paid,$2.99,Everyone,Education,"April 15, 2016",3.0 and up
2,Popsicle Launcher for Android P 9.0 launcher,PERSONALIZATION,NaN,0,5.50,0,Paid,$1.49,Everyone,Personalization,"July 11, 2018",4.2 and up
3,Command & Conquer: Rivals,FAMILY,NaN,0,19.00,0,NaN,0,Everyone 10+,Strategy,"June 28, 2018",Varies with device
4,CX Network,BUSINESS,NaN,0,10.00,0,Free,0,Everyone,Business,"August 6, 2018",4.1 and up

# Data Cleaning

**Challenge**: How many rows and columns does `df_apps` have? What are the column names? Look at a random sample of 5 different rows with [.sample()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sample.html).

In [237]:
df_apps.shape

(10841, 12)

In [238]:
df_apps.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size_MBs', 'Installs', 'Type',
       'Price', 'Content_Rating', 'Genres', 'Last_Updated', 'Android_Ver'],
      dtype='str')

In [239]:
df_apps.sample(5)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Android_Ver
6119,JW Caleb y Sofia,FAMILY,4.60,5227,1.90,"500,000",Free,0,Everyone,Education,"November 20, 2015",4.0.3 and up
6190,CW Seed,ENTERTAINMENT,4.50,16372,13.00,"500,000",Free,0,Teen,Entertainment,"July 18, 2018",4.4 and up
1867,BZ Conferencing,TOOLS,4.70,7,29.00,"1,000",Free,0,Everyone,Tools,"June 27, 2018",4.1 and up
9912,Dude Perfect 2,GAME,4.50,401425,70.00,"10,000,000",Free,0,Everyone,Action,"April 12, 2017",4.0.3 and up
4452,C++ Tutorials,EDUCATION,4.10,358,1.90,"50,000",Free,0,Everyone,Education,"August 21, 2014",2.3 and up

### Drop Unused Columns

**Challenge**: Remove the columns called `Last_Updated` and `Android_Version` from the DataFrame. We will not use these columns.

In [240]:
df_apps.drop(columns=["Last_Updated", "Android_Ver"], inplace=True)
df_apps.head()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
0,Ak Parti Yardım Toplama,SOCIAL,NaN,0,8.70,0,Paid,$13.99,Teen,Social
1,Ain Arabic Kids Alif Ba ta,FAMILY,NaN,0,33.00,0,Paid,$2.99,Everyone,Education
2,Popsicle Launcher for Android P 9.0 launcher,PERSONALIZATION,NaN,0,5.50,0,Paid,$1.49,Everyone,Personalization
3,Command & Conquer: Rivals,FAMILY,NaN,0,19.00,0,NaN,0,Everyone 10+,Strategy
4,CX Network,BUSINESS,NaN,0,10.00,0,Free,0,Everyone,Business

### Find and Remove NaN values in Ratings

**Challenge**: How may rows have a NaN value (not-a-number) in the Ratings column? Create DataFrame called `df_apps_clean` that does not include these rows.

In [241]:
df_apps_clean = df_apps.copy()
df_apps_clean["Rating"].isna().sum()

np.int64(1474)

In [242]:
df_apps_clean = df_apps_clean.dropna(subset=["Rating"])
df_apps_clean.shape

(9367, 10)

### Find and Remove Duplicates

**Challenge**: Are there any duplicates in data? Check for duplicates using the [.duplicated()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.duplicated.html) function. How many entries can you find for the "Instagram" app? Use [.drop_duplicates()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop_duplicates.html) to remove any duplicates from `df_apps_clean`.

In [243]:
df_apps_clean.duplicated().sum()

np.int64(476)

In [244]:
df_apps_clean[df_apps_clean["App"]=="Instagram"]

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
10806,Instagram,SOCIAL,4.50,66577313,5.30,"1,000,000,000",Free,0,Teen,Social
10808,Instagram,SOCIAL,4.50,66577446,5.30,"1,000,000,000",Free,0,Teen,Social
10809,Instagram,SOCIAL,4.50,66577313,5.30,"1,000,000,000",Free,0,Teen,Social
10810,Instagram,SOCIAL,4.50,66509917,5.30,"1,000,000,000",Free,0,Teen,Social

In [245]:
df_apps_clean.drop_duplicates(subset=["App", "Type", "Price"], inplace=True)
df_apps_clean.shape

(8199, 10)

# Find Highest Rated Apps

**Challenge**: Identify which apps are the highest rated. What problem might you encounter if you rely exclusively on ratings alone to determine the quality of an app?

In [246]:
df_apps_clean.sort_values(by="Rating", ascending=False)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
21,KBA-EZ Health Guide,MEDICAL,5.00,4,25.00,1,Free,0,Everyone,Medical
1751,Spine- The dating app,DATING,5.00,5,9.30,500,Free,0,Teen,Dating
1761,Selfie With Champion AJ Style,PHOTOGRAPHY,5.00,2,7.50,500,Free,0,Everyone,Photography
1763,Ag Valley Cooperative,BUSINESS,5.00,6,74.00,500,Free,0,Everyone,Business
1769,Yazdani Cd Center EllahAbad Official App,FAMILY,5.00,8,3.80,500,Free,0,Everyone,Entertainment
...,...,...,...,...,...,...,...,...,...,...
818,Familial Hypercholesterolaemia Handbook,MEDICAL,1.00,2,33.00,100,Free,0,Everyone,Medical
1208,Thistletown CI,PRODUCTIVITY,1.00,1,6.60,100,Free,0,Everyone,Productivity
1314,CR Magazine,BUSINESS,1.00,1,7.80,100,Free,0,Everyone,Business
1679,CB Mobile Biz,FINANCE,1.00,3,8.40,500,Free,0,Everyone,Finance
1721,Lottery Ticket Checker - Florida Results & Lotto,TOOLS,1.00,3,41.00,500,Free,0,Everyone,Tools

# Find 5 Largest Apps in terms of Size (MBs)

**Challenge**: What's the size in megabytes (MB) of the largest Android apps in the Google Play Store. Based on the data, do you think there could be limit in place or can developers make apps as large as they please?

In [247]:
df_apps_clean.sort_values(by="Size_MBs", ascending=False)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
8719,Draft Simulator for FUT 18,SPORTS,4.60,162933,100.00,"5,000,000",Free,0,Everyone,Sports
8718,Mini Golf King - Multiplayer Game,GAME,4.50,531458,100.00,"5,000,000",Free,0,Everyone,Sports
10295,SimCity BuildIt,FAMILY,4.50,4218587,100.00,"50,000,000",Free,0,Everyone 10+,Simulation
9945,Ultimate Tennis,SPORTS,4.30,183004,100.00,"10,000,000",Free,0,Everyone,Sports
9944,Gangster Town: Vice District,FAMILY,4.30,65146,100.00,"10,000,000",Free,0,Mature 17+,Simulation
...,...,...,...,...,...,...,...,...,...,...
5798,ExDialer PRO Key,COMMUNICATION,4.50,5474,0.02,"100,000",Paid,$3.99,Everyone,Communication
2648,Ad Remove Plugin for App2SD,PRODUCTIVITY,4.10,66,0.02,"1,000",Paid,$1.29,Everyone,Productivity
2684,My baby firework (Remove ad),FAMILY,4.10,30,0.01,"1,000",Paid,$0.99,Everyone,Entertainment
7966,Market Update Helper,LIBRARIES_AND_DEMO,4.10,20145,0.01,"1,000,000",Free,0,Everyone,Libraries & Demo
4696,Essential Resources,LIBRARIES_AND_DEMO,4.60,237,0.01,"50,000",Free,0,Everyone,Libraries & Demo

# Find the 5 App with Most Reviews

**Challenge**: Which apps have the highest number of reviews? Are there any paid apps among the top 50?

In [248]:
df_apps_clean.sort_values(by="Reviews", ascending=False)[:5]

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
10805,Facebook,SOCIAL,4.10,78158306,5.30,"1,000,000,000",Free,0,Teen,Social
10785,WhatsApp Messenger,COMMUNICATION,4.40,69119316,3.50,"1,000,000,000",Free,0,Everyone,Communication
10806,Instagram,SOCIAL,4.50,66577313,5.30,"1,000,000,000",Free,0,Teen,Social
10784,Messenger – Text and Video Chat for Free,COMMUNICATION,4.00,56642847,3.50,"1,000,000,000",Free,0,Everyone,Communication
10650,Clash of Clans,GAME,4.60,44891723,98.00,"100,000,000",Free,0,Everyone 10+,Strategy

In [249]:
df_apps_clean.sort_values(by="Reviews", ascending=False)[:50][df_apps_clean["Type"]!="Free"].count().any()

/tmp/ipykernel_2097425/2468431194.py:1: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

np.False_

# Plotly Pie and Donut Charts - Visualise Categorical Data: Content Ratings

In [250]:
ratings = df_apps_clean.Content_Rating.value_counts()
ratings

Content_Rating
Everyone           6621
Teen                912
Mature 17+          357
Everyone 10+        305
Adults only 18+       3
Unrated               1
Name: count, dtype: int64

In [251]:
fig = px.pie(labels=ratings.index, values=ratings.values)
fig.show()

In [252]:
fig = px.pie(labels=ratings.index,
values=ratings.values,
title="Content Rating",
names=ratings.index,
hole=0.6
)
fig.update_traces(textposition='outside', textinfo='percent+label')
    
fig.show()

# Numeric Type Conversion: Examine the Number of Installs

**Challenge**: How many apps had over 1 billion (that's right - BILLION) installations? How many apps just had a single install? 

Check the datatype of the Installs column.

Count the number of apps at each level of installations. 

Convert the number of installations (the Installs column) to a numeric data type. Hint: this is a 2-step process. You'll have make sure you remove non-numeric characters first.

In [253]:
df_apps_clean.head()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
21,KBA-EZ Health Guide,MEDICAL,5.00,4,25.00,1,Free,0,Everyone,Medical
28,Ra Ga Ba,GAME,5.00,2,20.00,1,Paid,$1.49,Everyone,Arcade
47,Mu.F.O.,GAME,5.00,2,16.00,1,Paid,$0.99,Everyone,Arcade
82,Brick Breaker BR,GAME,5.00,7,19.00,5,Free,0,Everyone,Arcade
99,Anatomy & Physiology Vocabulary Exam Review App,MEDICAL,5.00,1,4.60,5,Free,0,Everyone,Medical

In [254]:
df_apps_clean.dtypes

App                   str
Category              str
Rating            float64
Reviews             int64
Size_MBs          float64
Installs              str
Type                  str
Price                 str
Content_Rating        str
Genres                str
dtype: object

In [255]:
type(df_apps_clean.iloc[0]["Installs"])

str

In [256]:
df_apps_clean.sort_values(by="Installs", ascending=False)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
10731,My Talking Tom,GAME,4.50,14891223,36.00,"500,000,000",Free,0,Everyone,Casual
10746,"Security Master - Antivirus, VPN, AppLock, Boo...",TOOLS,4.70,24900999,3.40,"500,000,000",Free,0,Everyone,Tools
10711,SHAREit - Transfer & Share,TOOLS,4.60,7790693,17.00,"500,000,000",Free,0,Everyone,Tools
10713,imo free video calls and chat,COMMUNICATION,4.30,4785892,11.00,"500,000,000",Free,0,Everyone,Communication
10717,Pou,GAME,4.30,10485308,24.00,"500,000,000",Free,0,Everyone,Casual
...,...,...,...,...,...,...,...,...,...,...
2403,CI Screwed - Icon Pack,PERSONALIZATION,4.70,19,6.40,"1,000",Free,0,Everyone,Personalization
2402,EG Movi,TOOLS,4.20,40,7.40,"1,000",Free,0,Everyone,Tools
28,Ra Ga Ba,GAME,5.00,2,20.00,1,Paid,$1.49,Everyone,Arcade
47,Mu.F.O.,GAME,5.00,2,16.00,1,Paid,$0.99,Everyone,Arcade
21,KBA-EZ Health Guide,MEDICAL,5.00,4,25.00,1,Free,0,Everyone,Medical

In [257]:
df_apps_clean["Installs"] = df_apps_clean["Installs"].str.replace(",", "", regex=False).astype("Int64")

In [258]:
df_apps_clean.dtypes

App                   str
Category              str
Rating            float64
Reviews             int64
Size_MBs          float64
Installs            Int64
Type                  str
Price                 str
Content_Rating        str
Genres                str
dtype: object

In [259]:
df_apps_clean[df_apps_clean["Installs"].isna()==True]

Empty DataFrame
Columns: [App, Category, Rating, Reviews, Size_MBs, Installs, Type, Price, Content_Rating, Genres]
Index: []

In [260]:
type(df_apps_clean.iloc[0]["Installs"])

numpy.int64

In [261]:
df_apps_clean.head()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
21,KBA-EZ Health Guide,MEDICAL,5.00,4,25.00,1,Free,0,Everyone,Medical
28,Ra Ga Ba,GAME,5.00,2,20.00,1,Paid,$1.49,Everyone,Arcade
47,Mu.F.O.,GAME,5.00,2,16.00,1,Paid,$0.99,Everyone,Arcade
82,Brick Breaker BR,GAME,5.00,7,19.00,5,Free,0,Everyone,Arcade
99,Anatomy & Physiology Vocabulary Exam Review App,MEDICAL,5.00,1,4.60,5,Free,0,Everyone,Medical

In [262]:
df_apps_clean.groupby("Installs").count().sort_values(by="Installs", ascending=False)

,App,Category,Rating,Reviews,Size_MBs,Type,Price,Content_Rating,Genres
Installs,,,,,,,,,
1000000000,20,20,20,20,20,20,20,20,20
500000000,24,24,24,24,24,24,24,24,24
100000000,189,189,189,189,189,189,189,189,189
50000000,202,202,202,202,202,202,202,202,202
10000000,933,933,933,933,933,933,933,933,933
5000000,607,607,607,607,607,607,607,607,607
1000000,1417,1417,1417,1417,1417,1417,1417,1417,1417
500000,504,504,504,504,504,504,504,504,504
100000,1096,1096,1096,1096,1096,1096,1096,1096,1096
50000,457,457,457,457,457,457,457,457,457
10000,988,988,988,988,988,988,988,988,988
5000,425,425,425,425,425,425,425,425,425
1000,698,698,698,698,698,698,698,698,698
500,199,199,199,199,199,199,199,199,199
100,303,303,303,303,303,303,303,303,303
50,56,56,56,56,56,56,56,56,56
10,69,69,69,69,69,69,69,69,69
5,9,9,9,9,9,9,9,9,9
1,3,3,3,3,3,3,3,3,3

# Find the Most Expensive Apps, Filter out the Junk, and Calculate a (ballpark) Sales Revenue Estimate

Let's examine the Price column more closely.

**Challenge**: Convert the price column to numeric data. Then investigate the top 20 most expensive apps in the dataset.

Remove all apps that cost more than $250 from the `df_apps_clean` DataFrame.

Add a column called 'Revenue_Estimate' to the DataFrame. This column should hold the price of the app times the number of installs. What are the top 10 highest grossing paid apps according to this estimate? Out of the top 10 highest grossing paid apps, how many are games?

In [263]:
df_apps_clean["Price"] = df_apps_clean["Price"].str.replace(",", "", regex=False)
df_apps_clean["Price"] = df_apps_clean["Price"].str.replace("$", "", regex=False)
df_apps_clean["Price"] = df_apps_clean["Price"].astype("float64")

In [264]:
df_apps_clean.sort_values(by="Price", ascending=False).head(20)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
3946,I'm Rich - Trump Edition,LIFESTYLE,3.60,275,7.30,10000,Paid,400.00,Everyone,Lifestyle
2394,I am Rich!,FINANCE,3.80,93,22.00,1000,Paid,399.99,Everyone,Finance
2461,I AM RICH PRO PLUS,FINANCE,4.00,36,41.00,1000,Paid,399.99,Everyone,Finance
1331,most expensive app (H),FAMILY,4.30,6,1.50,100,Paid,399.99,Everyone,Entertainment
3145,I am rich(premium),FINANCE,3.50,472,0.94,5000,Paid,399.99,Everyone,Finance
2775,I Am Rich Pro,FAMILY,4.40,201,2.70,5000,Paid,399.99,Everyone,Entertainment
5765,I am rich,LIFESTYLE,3.80,3547,1.80,100000,Paid,399.99,Everyone,Lifestyle
3221,I am Rich Plus,FAMILY,4.00,856,8.70,10000,Paid,399.99,Everyone,Entertainment
3554,💎 I'm rich,LIFESTYLE,3.80,718,26.00,10000,Paid,399.99,Everyone,Lifestyle
3114,I am Rich,FINANCE,4.30,180,3.80,5000,Paid,399.99,Everyone,Finance
4606,I Am Rich Premium,FINANCE,4.10,1867,4.70,50000,Paid,399.99,Everyone,Finance
1946,I am rich (Most expensive app),FINANCE,4.10,129,2.70,1000,Paid,399.99,Teen,Finance
3897,I Am Rich,FAMILY,3.60,217,4.90,10000,Paid,389.99,Everyone,Entertainment
2193,I am extremely Rich,LIFESTYLE,2.90,41,2.90,1000,Paid,379.99,Everyone,Lifestyle
3856,I am rich VIP,LIFESTYLE,3.80,411,2.60,10000,Paid,299.99,Everyone,Lifestyle
2281,Vargo Anesthesia Mega App,MEDICAL,4.60,92,32.00,1000,Paid,79.99,Everyone,Medical
1407,LTC AS Legal,MEDICAL,4.00,6,1.30,100,Paid,39.99,Everyone,Medical
2629,I am Rich Person,LIFESTYLE,4.20,134,1.80,1000,Paid,37.99,Everyone,Lifestyle
2481,A Manual of Acupuncture,MEDICAL,3.50,214,68.00,1000,Paid,33.99,Everyone,Medical
2207,EMT PASS,MEDICAL,3.40,51,2.40,1000,Paid,29.99,Everyone,Medical

### The most expensive apps sub $250

In [265]:
df_apps_clean = df_apps_clean[df_apps_clean["Price"] <= 250]
df_apps_clean

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
21,KBA-EZ Health Guide,MEDICAL,5.00,4,25.00,1,Free,0.00,Everyone,Medical
28,Ra Ga Ba,GAME,5.00,2,20.00,1,Paid,1.49,Everyone,Arcade
47,Mu.F.O.,GAME,5.00,2,16.00,1,Paid,0.99,Everyone,Arcade
82,Brick Breaker BR,GAME,5.00,7,19.00,5,Free,0.00,Everyone,Arcade
99,Anatomy & Physiology Vocabulary Exam Review App,MEDICAL,5.00,1,4.60,5,Free,0.00,Everyone,Medical
...,...,...,...,...,...,...,...,...,...,...
10824,Google Drive,PRODUCTIVITY,4.40,2731171,4.00,1000000000,Free,0.00,Everyone,Productivity
10828,YouTube,VIDEO_PLAYERS,4.30,25655305,4.65,1000000000,Free,0.00,Teen,Video Players & Editors
10829,Google Play Movies & TV,VIDEO_PLAYERS,3.70,906384,4.65,1000000000,Free,0.00,Teen,Video Players & Editors
10831,Google News,NEWS_AND_MAGAZINES,3.90,877635,13.00,1000000000,Free,0.00,Teen,News & Magazines
10835,Subway Surfers,GAME,4.50,27722264,76.00,1000000000,Free,0.00,Everyone 10+,Arcade

### Highest Grossing Paid Apps (ballpark estimate)

In [266]:
df_apps_clean["Revenue_Estimate"] = df_apps_clean["Price"] * df_apps_clean["Installs"]
df_apps_clean.sort_values(by="Revenue_Estimate", ascending=False).head(10)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Revenue_Estimate
9220,Minecraft,FAMILY,4.50,2376564,19.00,10000000,Paid,6.99,Everyone 10+,Arcade;Action & Adventure,"69,900,000.00"
8825,Hitman Sniper,GAME,4.60,408292,29.00,10000000,Paid,0.99,Mature 17+,Action,"9,900,000.00"
7151,Grand Theft Auto: San Andreas,GAME,4.40,348962,26.00,1000000,Paid,6.99,Mature 17+,Action,"6,990,000.00"
7477,Facetune - For Free,PHOTOGRAPHY,4.40,49553,48.00,1000000,Paid,5.99,Everyone,Photography,"5,990,000.00"
7977,Sleep as Android Unlock,LIFESTYLE,4.50,23966,0.85,1000000,Paid,5.99,Everyone,Lifestyle,"5,990,000.00"
6594,DraStic DS Emulator,GAME,4.60,87766,12.00,1000000,Paid,4.99,Everyone,Action,"4,990,000.00"
6082,Weather Live,WEATHER,4.50,76593,4.75,500000,Paid,5.99,Everyone,Weather,"2,995,000.00"
6746,Card Wars - Adventure Time,FAMILY,4.30,129603,23.00,1000000,Paid,2.99,Everyone 10+,Card;Action & Adventure,"2,990,000.00"
7633,Five Nights at Freddy's,GAME,4.60,100805,50.00,1000000,Paid,2.99,Teen,Action,"2,990,000.00"
7954,Bloons TD 5,FAMILY,4.60,190086,94.00,1000000,Paid,2.99,Everyone,Strategy,"2,990,000.00"

# Plotly Bar Charts & Scatter Plots: Analysing App Categories

In [267]:
df_apps_clean.Category.nunique()

33

In [271]:
top10_category = df_apps_clean.Category.value_counts()[:10]
top10_category

Category
FAMILY             1606
GAME                910
TOOLS               719
PRODUCTIVITY        301
PERSONALIZATION     298
LIFESTYLE           297
FINANCE             296
MEDICAL             292
PHOTOGRAPHY         263
BUSINESS            262
Name: count, dtype: int64

In [277]:
type(top10_category)

pandas.Series

### Vertical Bar Chart - Highest Competition (Number of Apps)

In [274]:
bar = px.bar(x=top10_category.index, y=top10_category.values)
bar.show()

### Horizontal Bar Chart - Most Popular Categories (Highest Downloads)

In [286]:
category_installs = df_apps_clean.groupby("Category").agg({"Installs": pd.Series.sum})
category_installs.sort_values(by="Installs", inplace=True)
category_installs

                        Installs
Category
EVENTS                  15949410
BEAUTY                  26916200
PARENTING               31116110
MEDICAL                 39162676
COMICS                  44931100
LIBRARIES_AND_DEMO      52083000
AUTO_AND_VEHICLES       53129800
HOUSE_AND_HOME          97082000
ART_AND_DESIGN         114233100
DATING                 140912410
FOOD_AND_DRINK         211677750
EDUCATION              352852000
WEATHER                361096500
FINANCE                455249400
MAPS_AND_NAVIGATION    503267560
LIFESTYLE              503611120
BUSINESS               692018120
SPORTS                1096431465
HEALTH_AND_FITNESS    1134006220
SHOPPING              1400331540
PERSONALIZATION       1532352930
BOOKS_AND_REFERENCE   1665791655
ENTERTAINMENT         2113660000
NEWS_AND_MAGAZINES    2369110650
TRAVEL_AND_LOCAL      2894859300
VIDEO_PLAYERS         3916897200
FAMILY                4437554490
PHOTOGRAPHY           4649143130
SOCIAL                5487841475
PRODUCTIVITY          5788070180
TOOLS                 8099724500
COMMUNICATION        11039241530
GAME                 13858762717

In [291]:
category_installs.shape

(33, 1)

In [293]:
h_bar = px.bar(x=category_installs.Installs, 
               y=category_installs.index, 
               orientation="h", 
               height=800)
h_bar.show()

In [294]:
h_bar = px.bar(x=category_installs.Installs, 
               y=category_installs.index, 
               orientation="h",
               height=800,
               title="Category Popularity")
h_bar.update_layout(xaxis_title='Number of Downloads', yaxis_title='Category')
h_bar.show()

### Category Concentration - Downloads vs. Competition

**Challenge**: 
* First, create a DataFrame that has the number of apps in one column and the number of installs in another:

<img src=https://imgur.com/uQRSlXi.png width="350">

* Then use the [plotly express examples from the documentation](https://plotly.com/python/line-and-scatter/) alongside the [.scatter() API reference](https://plotly.com/python-api-reference/generated/plotly.express.scatter.html)to create scatter plot that looks like this. 

<img src=https://imgur.com/cHsqh6a.png>

*Hint*: Use the size, hover_name and color parameters in .scatter(). To scale the yaxis, call .update_layout() and specify that the yaxis should be on a log-scale like so: yaxis=dict(type='log')

In [295]:
df_apps_clean.head()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Revenue_Estimate
21,KBA-EZ Health Guide,MEDICAL,5.00,4,25.00,1,Free,0.00,Everyone,Medical,0.00
28,Ra Ga Ba,GAME,5.00,2,20.00,1,Paid,1.49,Everyone,Arcade,1.49
47,Mu.F.O.,GAME,5.00,2,16.00,1,Paid,0.99,Everyone,Arcade,0.99
82,Brick Breaker BR,GAME,5.00,7,19.00,5,Free,0.00,Everyone,Arcade,0.00
99,Anatomy & Physiology Vocabulary Exam Review App,MEDICAL,5.00,1,4.60,5,Free,0.00,Everyone,Medical,0.00

In [309]:
apps_and_installs = df_apps_clean.groupby(by="Category").agg({"App": pd.Series.count, "Installs": pd.Series.sum})
apps_and_installs.sort_values(by="Installs", inplace=True)
apps_and_installs

                      App     Installs
Category
EVENTS                 45     15949410
BEAUTY                 42     26916200
PARENTING              50     31116110
MEDICAL               292     39162676
COMICS                 54     44931100
LIBRARIES_AND_DEMO     64     52083000
AUTO_AND_VEHICLES      73     53129800
HOUSE_AND_HOME         62     97082000
ART_AND_DESIGN         61    114233100
DATING                134    140912410
FOOD_AND_DRINK         94    211677750
EDUCATION             118    352852000
WEATHER                72    361096500
FINANCE               296    455249400
MAPS_AND_NAVIGATION   118    503267560
LIFESTYLE             297    503611120
BUSINESS              262    692018120
SPORTS                260   1096431465
HEALTH_AND_FITNESS    243   1134006220
SHOPPING              180   1400331540
PERSONALIZATION       298   1532352930
BOOKS_AND_REFERENCE   169   1665791655
ENTERTAINMENT         102   2113660000
NEWS_AND_MAGAZINES    204   2369110650
TRAVEL_AND_LOCAL      187   2894859300
VIDEO_PLAYERS         148   3916897200
FAMILY               1606   4437554490
PHOTOGRAPHY           263   4649143130
SOCIAL                203   5487841475
PRODUCTIVITY          301   5788070180
TOOLS                 719   8099724500
COMMUNICATION         257  11039241530
GAME                  910  13858762717

In [323]:
apps_and_installs.index[0]

'EVENTS'

In [329]:
fig = px.scatter(x=apps_and_installs.App,
                 y=apps_and_installs.Installs,
                 color=apps_and_installs.Installs,
                 size=apps_and_installs.App,
                 hover_name=apps_and_installs.index,
                 log_y=True,
                 title="Category Concentration"
                 )

fig.update_layout(xaxis_title='Number of Apps (Lower = More concentrated)', yaxis_title='Installs')

fig.show()

# Extracting Nested Data from a Column

**Challenge**: How many different types of genres are there? Can an app belong to more than one genre? Check what happens when you use .value_counts() on a column with nested values? See if you can work around this problem by using the .split() function and the DataFrame's [.stack() method](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.stack.html).

In [331]:
df_apps_clean.Genres.value_counts()

Genres
Tools                       718
Entertainment               467
Education                   429
Productivity                301
Personalization             298
                           ...
Casual;Music & Video          1
Tools;Education               1
Role Playing;Brain Games      1
Adventure;Education           1
Lifestyle;Pretend Play        1
Name: count, Length: 114, dtype: int64

In [333]:
len(df_apps_clean.Genres.unique())

114

In [341]:
df_apps_clean.Genres

21                       Medical
28                        Arcade
47                        Arcade
82                        Arcade
99                       Medical
                  ...
10824               Productivity
10828    Video Players & Editors
10829    Video Players & Editors
10831           News & Magazines
10835                     Arcade
Name: Genres, Length: 8184, dtype: str

In [376]:
stack = df_apps_clean.Genres.str.split(';', expand=True).stack()
stack

21     0             Medical
       1                 NaN
28     0              Arcade
       1                 NaN
47     0              Arcade
                  ...
10829  1                 NaN
10831  0    News & Magazines
       1                 NaN
10835  0              Arcade
       1                 NaN
Length: 16368, dtype: str

In [378]:
stack.nunique()

53

In [379]:
len(stack.value_counts())

53

In [392]:
stack.value_counts()

Tools                      719
Education                  587
Entertainment              498
Action                     304
Productivity               301
Lifestyle                  298
Personalization            298
Finance                    296
Medical                    292
Sports                     270
Photography                263
Business                   262
Communication              258
Health & Fitness           245
Casual                     216
News & Magazines           204
Social                     203
Simulation                 200
Travel & Local             187
Arcade                     185
Shopping                   180
Books & Reference          171
Video Players & Editors    150
Dating                     134
Puzzle                     124
Maps & Navigation          118
Role Playing               111
Racing                     103
Action & Adventure          96
Strategy                    95
Food & Drink                94
Educational                 93
Adventure                   78
Auto & Vehicles             73
Weather                     72
Pretend Play                68
Brain Games                 65
Libraries & Demo            64
Art & Design                62
House & Home                62
Board                       57
Comics                      54
Parenting                   50
Card                        46
Events                      45
Beauty                      42
Casino                      37
Creativity                  31
Music & Video               31
Trivia                      28
Word                        22
Music                       21
Music & Audio                1
Name: count, dtype: int64

In [399]:
genres = stack.value_counts()

# Colour Scales in Plotly Charts - Competition in Genres

**Challenge**: Can you create this chart with the Series containing the genre data? 

<img src=https://imgur.com/DbcoQli.png width=400>

Try experimenting with the built in colour scales in Plotly. You can find a full list [here](https://plotly.com/python/builtin-colorscales/). 

* Find a way to set the colour scale using the color_continuous_scale parameter. 
* Find a way to make the color axis disappear by using coloraxis_showscale.

In [409]:
bar = px.bar(x=genres.index,
             y=genres.values,
             title="Top Genres",
             hover_name=genres.index,
             color=genres.values,
             color_continuous_scale=px.colors.sequential.Agsunset)

bar.update_xaxes(tickangle=45)

bar.update_layout(xaxis_title='Genre', 
                  yaxis_title='Number of Apps',
                  coloraxis_showscale=False
                  )

bar.show()

# Grouped Bar Charts: Free vs. Paid Apps per Category

In [411]:
df_apps_clean.Type.value_counts()

Type
Free    7595
Paid     589
Name: count, dtype: int64

In [425]:
df_free_vs_paid = df_apps_clean.groupby(["Category", "Type"], as_index=False).agg({'App': pd.Series.count})
df_free_vs_paid.sort_values(by="App", ascending=False, inplace=True)
df_free_vs_paid.head()

     Category  Type   App
19     FAMILY  Free  1456
25       GAME  Free   834
53      TOOLS  Free   656
21    FINANCE  Free   289
31  LIFESTYLE  Free   284

In [429]:
df_free_vs_paid.columns

Index(['Category', 'Type', 'App'], dtype='str')

In [444]:
bar = px.bar(x=df_free_vs_paid.Category,
             y=df_free_vs_paid.App,
             title="Free vs Paid Apps by Category",
             barmode='group',
             color=df_free_vs_paid.Type,
             log_y=True)

bar.update_xaxes(categoryorder='total descending',
                 tickangle=90)

bar.update_layout(xaxis_title='Category', 
                  yaxis_title='Number of Apps',
                  coloraxis_showscale=False
                  )

bar.show()

**Challenge**: Use the plotly express bar [chart examples](https://plotly.com/python/bar-charts/#bar-chart-with-sorted-or-ordered-categories) and the [.bar() API reference](https://plotly.com/python-api-reference/generated/plotly.express.bar.html#plotly.express.bar) to create this bar chart: 

<img src=https://imgur.com/LE0XCxA.png>

You'll want to use the `df_free_vs_paid` DataFrame that you created above that has the total number of free and paid apps per category. 

See if you can figure out how to get the look above by changing the `categoryorder` to 'total descending' as outlined in the documentation here [here](https://plotly.com/python/categorical-axes/#automatically-sorting-categories-by-name-or-total-value).

# Plotly Box Plots: Lost Downloads for Paid Apps

**Challenge**: Create a box plot that shows the number of Installs for free versus paid apps. How does the median number of installations compare? Is the difference large or small?

Use the [Box Plots Guide](https://plotly.com/python/box-plots/) and the [.box API reference](https://plotly.com/python-api-reference/generated/plotly.express.box.html) to create the following chart. 

<img src=https://imgur.com/uVsECT3.png>

In [447]:
df_apps_clean.head()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Revenue_Estimate
21,KBA-EZ Health Guide,MEDICAL,5.00,4,25.00,1,Free,0.00,Everyone,Medical,0.00
28,Ra Ga Ba,GAME,5.00,2,20.00,1,Paid,1.49,Everyone,Arcade,1.49
47,Mu.F.O.,GAME,5.00,2,16.00,1,Paid,0.99,Everyone,Arcade,0.99
82,Brick Breaker BR,GAME,5.00,7,19.00,5,Free,0.00,Everyone,Arcade,0.00
99,Anatomy & Physiology Vocabulary Exam Review App,MEDICAL,5.00,1,4.60,5,Free,0.00,Everyone,Medical,0.00

In [461]:
fig = px.box(df_apps_clean,
             x="Type",
             y="Installs",
             color="Type",
             notched=True,
             title="How Many Downloads are Paid Apps Giving Up?",
             points='all',
             log_y=True,
             height=800
             )
fig.show()

# Plotly Box Plots: Revenue by App Category

**Challenge**: See if you can generate the chart below: 

<img src=https://imgur.com/v4CiNqX.png>

Looking at the hover text, how much does the median app earn in the Tools category? If developing an Android app costs $30,000 or thereabouts, does the average photography app recoup its development costs?

Hint: I've used 'min ascending' to sort the categories.

In [463]:
df_apps_clean.head()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Revenue_Estimate
21,KBA-EZ Health Guide,MEDICAL,5.00,4,25.00,1,Free,0.00,Everyone,Medical,0.00
28,Ra Ga Ba,GAME,5.00,2,20.00,1,Paid,1.49,Everyone,Arcade,1.49
47,Mu.F.O.,GAME,5.00,2,16.00,1,Paid,0.99,Everyone,Arcade,0.99
82,Brick Breaker BR,GAME,5.00,7,19.00,5,Free,0.00,Everyone,Arcade,0.00
99,Anatomy & Physiology Vocabulary Exam Review App,MEDICAL,5.00,1,4.60,5,Free,0.00,Everyone,Medical,0.00

In [478]:
df_paid_apps = df_apps_clean[df_apps_clean["Type"]=="Paid"]

In [480]:
fig = px.box(df_paid_apps,
             x="Category",
             y="Revenue_Estimate",
             title="How Much Can Paid Apps Earn?",
             log_y=True)

fig.update_xaxes(categoryorder='min ascending')

fig.update_layout(xaxis_title='Category', 
                  yaxis_title='Paid App Ballpark Revenue',
                  coloraxis_showscale=False
                  )

fig.show()

# How Much Can You Charge? Examine Paid App Pricing Strategies by Category

**Challenge**: What is the median price price for a paid app? Then compare pricing by category by creating another box plot. But this time examine the prices (instead of the revenue estimates) of the paid apps. I recommend using `{categoryorder':'max descending'}` to sort the categories.

In [483]:
fig = px.box(df_paid_apps,
             x="Category",
             y="Price",
             title="How Much Can Paid Apps Earn?",
             log_y=True)

fig.update_xaxes(categoryorder='max descending')

fig.update_layout(xaxis_title='Category', 
                  yaxis_title='Paid App Price',
                  coloraxis_showscale=False
                  )

fig.show()

In [485]:
df_paid_apps.Price.mean()

np.float64(4.476468590831919)

In [484]:
df_paid_apps.Price.median()

np.float64(2.99)